//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickFarm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickFarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chromedriver {
            get {
                object obj = ResourceManager.GetObject("chromedriver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24/2020 8:58:51 PM: Playing playlist at https://open.spotify.com/playlist/1hgGEYBYYKcnbhzUjDvqA5
        ///7/24/2020 8:58:54 PM: Playing for 58 seconds
        ///7/24/2020 9:23:00 PM: Playing playlist at https://open.spotify.com/playlist/1hgGEYBYYKcnbhzUjDvqA5
        ///7/24/2020 9:23:03 PM: Playing for 42 seconds
        ///7/24/2020 9:23:48 PM: Playing for 39 seconds
        ///7/24/2020 9:24:31 PM: Playing for 46 seconds
        ///7/24/2020 9:25:20 PM: Playing for 50 seconds
        ///7/24/2020 9:26:14 PM: Playing for 40 seconds
        ///7/24/2020 9:26:58 PM: Playing for 43 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist:https://open.spotify.com/playlist/1hgGEYBYYKcnbhzUjDvqA5.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msedgedriver {
            get {
                object obj = ResourceManager.GetObject("msedgedriver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] operadriver {
            get {
                object obj = ResourceManager.GetObject("operadriver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucflwgxqdtprpxdxnm@awdrt.net.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
